function [dat, fsample, onset, value] = audio_trigger_detect(filename, varargin)

% AUDIO_TRIGGER_DETECT
%
% Use as
%   [dat, fsample, onset, value] = audio_trigger_detect(filename, varargin)
% to get the output variables. Additional options are:
%       'vis'       = visualization of the audiodata and trigger detection
%       (default = 0)
%       'threshold' = threshold used for event detection (default = 0.1)
%       'dat' & 'fsample' = data and fsample generated by the previous
%       round of audio_trigger_detect to speed up the process
%       'correction' = what to do with events that were not within the
%       suspected duration limits (between [0.19-0.21] or [0.49-0.51] sec.
%       Start with correction 'none', if error, change correction to 'remove'or
%       'combine'

%% get options
correction=ft_getopt(varargin, 'correction', 'none');
dat=ft_getopt(varargin, 'data');
fsample=ft_getopt(varargin, 'fsample');
threshold=ft_getopt(varargin, 'threshold', 0.1); % default threshold is 0.1
vis=ft_getopt(varargin, 'visualize', true);

[p, f, x] = fileparts(filename);

%% Load audio data
if isempty(dat)
    fprintf('audio_trigger_detect for %s \n', f)
    fprintf('loading in the audio data... \n');
    [dat, fsample]=audioread(filename);
else
    fprintf('using the provided data \n')
end

%% preprocess data
fprintf('preprocessing the audio data... \n');
dat_cleaned=dat(:,1)-dat(:,2);
if vis
    x=[0:1/fsample:(size(dat,1)-1)/fsample];
    figure; plot(x, dat_cleaned); title(f);
end
dat_flt = ft_preproc_lowpassfilter(abs(ft_preproc_highpassfilter(dat_cleaned', fsample, 800)), fsample, 800);
if vis
    hold on; plot(x, dat_flt); legend({'cleaned data', 'filtered data'})
end
%% define events
dat_thr = dat_flt>threshold;
if vis
    hold on; plot(x,0.5*dat_thr, '.', 'DisplayName', 'detected events')
end

onset  = find([0 diff(dat_thr)]== 1); % in samples
offset = find([0 diff(dat_thr)]==-1); % in samples
duration = (offset-onset)/fsample; % in seconds

%% switch between correction options
switch correction
    case 'none'
        % check if all events are defined properly (0.2 sec or 0.5 sec)
        idx=find(duration<0.19|(duration>0.21&duration<0.49)|duration>0.51);
        if any(idx)
            warning('Not all detected beeps were 0.2 or 0.5 seconds. Possibly some wrong events were detected at time point (seconds from start):')
            table((onset(idx)/fsample)', duration(idx)','VariableNames', {'onset', 'duration'})
            warning('Treating the detected event as a valid event. You can change this by changing correction to remove or combine')
        end
        
    case 'remove' %throw away the detected events with different duration
        idx=find(duration<0.19|(duration>0.21&duration<0.49)|duration>0.51);
        if any(idx)
            warning('Not all detected beeps were 0.5 seconds. You decided to remove following events:')
            table((onset(idx)/fsample)', duration(idx)','VariableNames', {'onset', 'duration'})
        end
        fprintf('removing event number %d \n', idx)
        onset(idx)=[];
        offset(idx)=[];
        duration(idx)=[];
        
    case 'combine' % combine the wrongly detected event with the closest one
        idx=find(duration<0.19|(duration>0.21&duration<0.49)|duration>0.51);
        if any(idx)
            warning('Not all detected beeps were 0.5 seconds. You decided to combine following events with the closest event:')
            table((onset(idx)/fsample)', duration(idx)','VariableNames', {'onset', 'duration'})
        end
        while ~isempty(idx)
            for i=idx
                if i==1 || onset(i+1)-offset(i) < onset(i)-offset(i-1) % closest event is the next one
                    fprintf('combining event %d with event %d \n', idx, idx+1)
                    dat_thr(1, onset(i):onset(i+1))=1; % combine with next event
                elseif i==length(onset) || onset(i+1)-offset(i) > onset(i)-offset(i-1) % closest event is the previous one
                    fprintf('combining event %d with event %d \n', idx, idx-1)
                    dat_thr(1, offset(i-1):onset(i))=1; % combine with previous event
                end
            end
            onset  = find([0 diff(dat_thr)]== 1); % in samples
            offset = find([0 diff(dat_thr)]==-1); % in samples
            duration = (offset-onset)/fsample; % in seconds
            %%
            idx=find(duration<0.19|(duration>0.21&duration<0.49)|duration>0.51);
            if ~isempty(idx)
                warning('Not all detected beeps were 0.5 seconds. Repeating previous steps... ')
            end
        end 
    
end

%% define trial types (see working principles/ground plan)
value = cell(numel(duration), 1);
for i=1:numel(duration)
    x = dat(onset(i):offset(i),1);
    [p, f] = pwelch(x,[],[],[],fsample);
    [m, indx] = max(p);
    freq=f(indx);
    if freq>3510 & freq<3530 % 3520 Hz
      if duration(i)>0.49 && duration(i)<0.51
        value{i} = 'start_run';
      elseif duration(i)>0.19 && duration(i)<0.21
        value{i} = 'stop_run';
      end
    elseif freq>1740 & freq<1770 % HC25, HC57 & HC42: 1750Hz for stop_block instead of 1760 Hz 
      if duration(i)>0.49 && duration(i)<0.51
        value{i} = 'start_block';
      elseif duration(i)>0.19 && duration(i)<0.21
        value{i} = 'stop_block';
      end
    elseif (freq>870 & freq<890) & (duration(i)>0.19 && duration(i)<0.21) % 880 Hz
        value{i}='sync';
    else
        warning('event %d is not recognized as start, stop or sync event', i)
    end
end

%% define onset in seconds
onset= [onset(:)-1]/fsample;
