function [dat, fsample, onset, value] = audio_trigger_detect(filename, varargin)

% AUDIO_TRIGGER_DETECT
%
% Use as
%   [dat, fsample, onset, value] = audio_trigger_detect(filename, varargin)
% to get the output variables. Additional options are:
%       'vis'       = visualization of the audiodata and trigger detection
%       (default = 1)
%       'threshold' = threshold used for event detection (default = 0.1)
%       'data' & 'fsample' = data and fsample generated by the previous
%       round of audio_trigger_detect to speed up the process
%       'correction' = what to do with events that were not within the
%       suspected duration limits (between [0.19-0.21] or [0.49-0.51] sec.
%       Start with correction 'none', if error, change correction to 'remove'or
%       'combine'

%% get options
correction=ft_getopt(varargin, 'correction', 'none');
dat=ft_getopt(varargin, 'data');
fsample=ft_getopt(varargin, 'fsample');
threshold=ft_getopt(varargin, 'threshold', 0.1); % default threshold is 0.1
vis=ft_getopt(varargin, 'vis', true);

[p, f, x] = fileparts(filename);
fparts=regexp(f, 'sub-(?<sub>\w+)_task-gait_acq-(?<acq>\w+)_rec-(?<rec>\d+)_video', 'names');

%% Load audio data
if isempty(dat)
    fprintf('audio_trigger_detect for %s \n', f)
    fprintf('loading in the audio data... \n');
    [dat, fsample]=audioread(filename);
else
    fprintf('using the provided data \n')
end

%% preprocess data
fprintf('preprocessing the audio data... \n');
dat_cleaned=dat(:,1)-dat(:,2);
if vis
    x=[0:1/fsample:(size(dat,1)-1)/fsample];
    figure; plot(x, dat_cleaned); title(sprintf('sub-%s acq-%s', fparts.sub, fparts.acq));
end
dat_flt = ft_preproc_lowpassfilter(abs(ft_preproc_highpassfilter(dat_cleaned', fsample, 800)), fsample, 800);
if vis
    hold on; plot(x, dat_flt); legend({'cleaned data', 'filtered data'})
end
%% define events
dat_thr = dat_flt>threshold;
if vis
    hold on; plot(x,0.5*dat_thr, '.', 'DisplayName', 'detected events')
end

onset  = find([0 diff(dat_thr)]== 1); % in samples
offset = find([0 diff(dat_thr)]==-1); % in samples
duration = (offset-onset)/fsample; % in seconds

%% switch between correction options
idx=find(duration<0.19|(duration>0.21&duration<0.49)|duration>0.51);
if strcmp(fparts.sub, 'PD35') & strcmp(fparts.acq, 'end')
  correction = 'remove';
elseif strcmp(fparts.sub, 'HC29') | strcmp(fparts.sub, 'HC04') | strcmp(fparts.sub, 'HC19')
  correction = 'split';
elseif strcmp(fparts.sub, 'HC60') & strcmp(fparts.acq, 'mobile')
  correction = 'remove';
elseif strcmp(fparts.sub, 'HC60') & strcmp(fparts.acq, 'end')
  correction = 'split';
elseif strcmp(fparts.sub, 'HC42')
  correction = 'combine_all';
elseif strcmp(fparts.sub, 'HC35')
  if strcmp(fparts.acq, 'begin')
    correction='split';
  elseif strcmp(fparts.acq, 'end')
    correction='split3';
  end
end
switch correction
    case 'none'
        % check if all events are defined properly (0.2 sec or 0.5 sec)
        if any(idx)
            warning('Not all detected beeps were 0.2 or 0.5 seconds. Possibly some wrong events were detected at time point (seconds from start):')
            table((onset(idx)/fsample)', duration(idx)','VariableNames', {'onset', 'duration'})
            warning('Treating the detected event as a valid event. You can change this by changing correction to remove or combine')
        end
        
    case 'remove' %throw away the detected events with different duration
        if any(idx)
            warning('Not all detected beeps were 0.2 or 0.5 seconds. You decided to remove following events:')
            table((onset(idx)/fsample)', duration(idx)','VariableNames', {'onset', 'duration'})
        end
        fprintf('removing event number %d \n', idx)
        onset(idx)=[];
        offset(idx)=[];
        duration(idx)=[];
        
    case 'combine' % combine the wrongly detected event with the closest one
        if any(idx)
            warning('Not all detected beeps were 0.2 or 0.5 seconds. You decided to combine following events with the closest event:')
            table((onset(idx)/fsample)', duration(idx)','VariableNames', {'onset', 'duration'})
        end
        while ~isempty(idx)
            for i=idx
                if i==1 || onset(i+1)-offset(i) < onset(i)-offset(i-1) % closest event is the next one
                    fprintf('combining event %d with event %d \n', idx, idx+1)
                    dat_thr(1, onset(i):onset(i+1))=1; % combine with next event
                elseif i==length(onset) || onset(i+1)-offset(i) > onset(i)-offset(i-1) % closest event is the previous one
                    fprintf('combining event %d with event %d \n', idx, idx-1)
                    dat_thr(1, offset(i-1):onset(i))=1; % combine with previous event
                end
            end
            onset  = find([0 diff(dat_thr)]== 1); % in samples
            offset = find([0 diff(dat_thr)]==-1); % in samples
            duration = (offset-onset)/fsample; % in seconds
            %%
            idx=find(duration<0.19|(duration>0.21&duration<0.49)|duration>0.51);
            if ~isempty(idx)
                warning('Not all detected beeps were 0.5 seconds. Repeating previous steps... ')
            end
        end 
        
  case 'combine_all' % combine all wrongly detected events with one event
    if any(idx)
      warning('Not all detected beeps were 0.2 or 0.5 seconds. You decided to combine following events to one event:')
      table((onset(idx)/fsample)', duration(idx)','VariableNames', {'onset', 'duration'})
    end
    onset = onset([1:idx(1) idx(end)+1:end]);
    offset = offset([1:idx(1)-1 idx(end):end]);
    duration=(offset-onset)/fsample;

  case 'split'
    if any(idx)
      warning('Not all detected beeps were 0.2 or 0.5 seconds. You decided to split following events:')
      table((onset(idx)/fsample)', duration(idx)','VariableNames', {'onset', 'duration'})
    end
    for i=1:length(idx)
      fprintf('Splitting event number %d \n', idx(i))
      onset = [onset(1:idx(i)) round(onset(idx(i))+duration(idx(i))*fsample/2) onset(idx(i)+1:end)];
      offset= [offset(1:idx(i)-1) round(onset(idx(i))+duration(idx(i))*fsample/2) offset(idx(i):end)];
      duration = (offset-onset)/fsample;
      idx=idx+1; % update index because one extra event was created
    end
  case 'split3'
    if any(idx)
      warning('Not all detected beeps were 0.2 or 0.5 seconds. You decided to split following events in three:')
      table((onset(idx)/fsample)', duration(idx)','VariableNames', {'onset', 'duration'})
    end
    for i=1:length(idx)
      fprintf('Splitting event number %d in three \n', idx(i))
      onset = [onset(1:idx(i)) round(onset(idx(i))+duration(idx(i))*fsample/3) round(onset(idx(i))+duration(idx(i))*fsample*2/3) onset(idx(i)+1:end)];
      offset= [offset(1:idx(i)-1) round(onset(idx(i))+duration(idx(i))*fsample/3) round(onset(idx(i))+duration(idx(i))*fsample*2/3) offset(idx(i):end)];
      duration = (offset-onset)/fsample;
      idx=idx+1; % update index because one extra event was created
    end
end

%% define trial types (see working principles/ground plan)
value = cell(numel(duration), 1);
for i=1:numel(duration)
    x = dat(onset(i):offset(i),1);
    [p, f] = pwelch(x,[],[],[],fsample);
    [m, indx] = max(p);
    freq=f(indx);
    if freq>3510 & freq<3530 % 3520 Hz
      if duration(i)>0.49 && duration(i)<0.51
        value{i} = 'start_run';
      elseif duration(i)>0.19 && duration(i)<0.21
        value{i} = 'stop_run';
      end
    elseif freq>1740 & freq<1770 % HC25, HC57 & HC42: 1750Hz for stop_block instead of 1760 Hz 
      if duration(i)>0.49 && duration(i)<0.51
        value{i} = 'start_block';
      elseif duration(i)>0.19 && duration(i)<0.21
        value{i} = 'stop_block';
      end
    elseif (freq>870 & freq<890) & (duration(i)>0.19 && duration(i)<0.21) % 880 Hz
        value{i}='sync';
    else
        warning('event %d is not recognized as start, stop or sync event', i)
    end
end

%% define onset in seconds
onset= [onset(:)-1]/fsample;
